Prompt 
Prompt Creando FKs en tabla AUT_TSURL

prompt FK_AUT_TSURL_AUT_TSERVICIO

ALTER TABLE "UDTESIS"."AUT_TSURL" 
ADD CONSTRAINT "FK_AUT_TSURL_AUT_TSERVICIO" 
FOREIGN KEY ("SURL_SERVICIO")
REFERENCES "UDTESIS"."AUT_TSERVICIO" ("SERVICIO_SERVICIO") ENABLE;