PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.CO_TPYFD

Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (5153, 1, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (5161, 1, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (5167, 1, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (5191, 1, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7111, 1, sysdate);


Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7169, 2, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7185, 2, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7196, 2, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7217, 2, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7242, 2, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7263, 2, sysdate);
Insert into FS_RECAUDOS_US.CO_TPYFD (PYFD_PROY,PYFD_FRDP,PYFD_FCREA) values (7278, 2, sysdate);

commit;