PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.FS_RECAUDOS_US.CO_TOFIC

insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('002','9002','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('003','9003','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('004','9004','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('006','9006','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('007','9007','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('009','9009','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('010','9010','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('011','9011','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('012','9012','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('013','9013','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('015','9015','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('016','9016','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('017','9017','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('018','9018','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('019','9019','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('020','9020','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('021','9021','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('022','9022','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('023','9023','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('024','9024','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('025','9025','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('026','9026','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('027','9027','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('028','9028','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('029','9029','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('032','9032','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('033','9033','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('034','9034','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('035','9035','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('036','9036','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('037','9037','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('038','9038','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('039','9039','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('040','9040','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('042','9042','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('043','9043','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('044','9044','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('045','9045','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('047','9047','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('048','9048','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('049','9049','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('050','9050','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('051','9051','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('052','9052','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('053','9053','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('054','9054','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('055','9055','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('057','9057','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('058','9058','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('059','9059','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('060','9060','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('061','9061','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('062','9062','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('063','9063','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('064','9064','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('067','9067','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('068','9068','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('069','9069','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('070','9070','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('071','9071','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('073','9073','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('074','9074','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('075','9075','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('076','9076','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('077','9077','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('079','9079','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('080','9080','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('081','9081','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('082','9082','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('083','9083','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('084','9084','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('086','9086','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('087','9087','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('090','9090','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('091','9091','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('092','9092','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('093','9093','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('094','9094','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('095','9095','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('096','9096','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('097','9097','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('098','9098','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('099','9099','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('100','9100','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('101','9101','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('102','9102','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('103','9103','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('104','9104','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('105','9105','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('106','9106','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('107','9107','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('108','9108','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('109','9109','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('110','9110','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('112','9112','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('113','9113','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('114','9114','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('116','9116','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('117','9117','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('118','9118','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('119','9119','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('120','9120','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('121','9121','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('122','9122','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('123','9123','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('125','9125','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('127','9127','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('129','9129','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('130','9130','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('131','9131','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('132','9132','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('133','9133','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('135','9135','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('136','9136','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('137','9137','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('138','9138','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('139','9139','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('140','9140','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('141','9141','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('142','9142','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('143','9143','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('144','9144','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('145','9145','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('146','9146','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('147','9147','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('148','9148','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('149','9149','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('150','9150','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('151','9151','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('155','9155','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('157','9157','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('158','9158','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('160','9160','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('162','9162','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('163','9163','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('164','9164','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('166','9166','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('167','9167','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('168','9168','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('169','9169','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('170','9170','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('171','9171','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('179','9179','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('181','9181','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('183','9183','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('184','9184','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('186','9186','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('191','9191','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('193','9193','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('201','9201','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('202','9202','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('203','9203','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('204','9204','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('206','9206','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('208','9208','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('209','9209','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('210','9210','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('211','9211','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('212','9212','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('214','9214','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('216','9216','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('218','9218','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('220','9220','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('222','9222','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('223','9223','Medellin Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('232','9232','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('241','9241','Medellin Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('247','9247','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('259','9259','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('270','9270','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('271','9271','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('272','9272','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('274','9274','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('336','9336','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('337','9337','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('338','9338','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('339','9339','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('340','9340','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('341','9341','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('342','9342','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('343','9343','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('344','9344','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('345','9345','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('346','9346','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('347','9347','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('348','9348','Cali Norte');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('407','9407','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('411','9411','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('412','9412','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('413','9413','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('414','9414','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('415','9415','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('416','9416','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('417','9417','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('421','9421','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('423','9423','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('426','9426','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('430','9430','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('431','9431','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('432','9432','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('435','9435','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('436','9436','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('437','9437','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('438','9438','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('449','9449','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('450','9450','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('451','9451','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('502','9502','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('503','9503','Cali Sur');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('504','9504','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('505','9505','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('506','9506','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('507','9507','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('508','9508','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('509','9509','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('510','9510','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('511','9511','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('512','9512','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('514','9514','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('515','9515','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('517','9517','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('518','9518','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('519','9519','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('520','9520','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('521','9521','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('523','9523','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('524','9524','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('525','9525','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('526','9526','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('527','9527','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('528','9528','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('529','9529','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('533','9533','Eje Cafetero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('534','9534','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('535','9535','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('539','9539','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('540','9540','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('541','9541','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('542','9542','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('543','9543','Central');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('545','9545','Costa');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('546','9546','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('548','9548','Oriente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('625','9625','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('626','9626','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('627','9627','Bogotá Suroriental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('628','9628','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('629','9629','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('630','9630','Andina');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('631','9631','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('632','9632','Barranquilla');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('634','9634','Bogotá Chapinero');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('635','9635','Bogotá Eje Industrial');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('636','9636','Occidente');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('637','9637','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('638','9638','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('640','9640','Bogotá Nororiental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('641','9641','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('642','9642','Bogotá Noroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('702','9702','Bogotá Occidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('711','9711','NA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('712','9712','NA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('713','9713','NA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('715','9715','NA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('731','9731','NA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('741','9741','NA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('552','9552','Bogotá Suroccidental');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('851','9851','Bogotá Centro');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('189','9189','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('442','9442','Sin descripcion');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('418','9418','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('419','9419','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('420','9420','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('444','9444','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('441','9441','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('443','9443','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('445','9445','Bogotá');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('439','9439','CMARCA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('448','9448','CMARCA');
insert into FS_RECAUDOS_US.CO_TOFIC(OFIC_BSC,OFIC_SIFI,OFIC_DESCRI) values ('447','9447','Bogotá');




commit;


