PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.CO_TEPFD

Insert into FS_RECAUDOS_US.CO_TEPFD (EPFD_FRDP,EPFD_ESTA,EPFD_FCREA) values (1, 'NO_SIFI_ACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPFD (EPFD_FRDP,EPFD_ESTA,EPFD_FCREA) values (2, 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPFD (EPFD_FRDP,EPFD_ESTA,EPFD_FCREA) values (2, 'PCA', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPFD (EPFD_FRDP,EPFD_ESTA,EPFD_FCREA) values (2, 'NO_SIFI_ACT', sysdate);
commit;