PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.CO_TEPSG

Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D10', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D10', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D10', 'PCA', sysdate);

Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D03', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D03', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D03', 'PCA', sysdate);


Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D42', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D42', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D42', 'PCA', sysdate);


Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D45', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D45', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D45', 'PCA', sysdate);


Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D66', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D66', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D66', 'PCA', sysdate);


Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D93', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D93', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D93', 'PCA', sysdate);



Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D25', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D25', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D25', 'PCA', sysdate);


Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D50', 'NO_SIFI_INACT', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D50', 'CAN', sysdate);
Insert into FS_RECAUDOS_US.CO_TEPSG (EPSG_TPAR,EPSG_ESTA,EPSG_FCREA) values ('D50', 'PCA', sysdate);

commit;