PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.FS_RECAUDOS_US.CO_TTPAR

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D42', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 1, 12, 'N', 'S', '01');

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D45', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 1213990902996, 12, 'N', 'S','01');

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D66', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 1213990902995, 12, 'N', 'S','01');

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D93', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 1213990902999, 12, 'N', 'S','01');

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D25', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 1213990902999, 12, 'N', 'S','01');

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D03', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 3112000000002, 10, 'N', 'N','01');

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D10', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 3112000000002, 10, 'N', 'N','01');

insert into FS_RECAUDOS_US.CO_TTPAR(TPAR_TPAR, TPAR_DESCRI, TPAR_USUA, TPAR_PLAN_GENERICO, TPAR_FONDO, TPAR_COMP_RF_SN, TPAR_USA_VOL_SN, TPAR_CTA_RECAUDO)
values ('D50', 'Nuevo tipo de archivo creado por proceso 80', 'operador', 1213990902998, 12, 'N', 'S','01');


commit;
