PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.AUT_TUROL

PROMPT ROLES USUARIO ADMINISTRADOR
Insert into FS_RECAUDOS_US.AUT_TUROL (UROL_USUA,UROL_ROL) values ('administrador','ADMIN');

PROMPT ROLES USUARIOS DE PRUEBAS
Insert into FS_RECAUDOS_US.AUT_TUROL (UROL_USUA,UROL_ROL) values ('operador','OPER');


commit;