Prompt 
Prompt Creando FKs en tabla AUT_TSERVICIO

prompt Llave Foranea
prompt FK_AUT_TSERVICIO_AUT_TMODULO

ALTER TABLE "FS_RECAUDOS_US"."AUT_TSERVICIO" 
ADD CONSTRAINT "FK_AUT_TSERVICIO_AUT_TMODULO" 
FOREIGN KEY ("SERVICIO_MODULO")
REFERENCES "FS_RECAUDOS_US"."AUT_TMODULO" ("MODULO_MODULO") ENABLE;