Prompt 
Prompt Creando FKs en tabla AUT_TUROL

prompt FK_AUT_TUROL_AUT_TROL

ALTER TABLE "FS_RECAUDOS_US"."AUT_TUROL" 
ADD CONSTRAINT "FK_AUT_TUROL_AUT_TROL" 
FOREIGN KEY ("UROL_ROL")
REFERENCES "FS_RECAUDOS_US"."AUT_TROL" ("ROL_ROL") ENABLE;

prompt FK_AUT_TUROL_AUT_TUSUA

ALTER TABLE "FS_RECAUDOS_US"."AUT_TUROL"
ADD CONSTRAINT "FK_AUT_TUROL_AUT_TUSUA" 
FOREIGN KEY ("UROL_USUA")
REFERENCES "FS_RECAUDOS_US"."AUT_TUSUA" ("USUA_USUA") ENABLE;