PROMPT CO_TARGE_FK.sql
@@CO_TARGE_FK.sql

PROMPT CO_TAROR_FK.sql
@@CO_TAROR_FK.sql

PROMPT CO_TDARGE_FK.sql
@@CO_TDARGE_FK.sql

PROMPT CO_TDAROR_FK.sql
@@CO_TDAROR_FK.sql

PROMPT CO_TDPFD_FK.sql
@@CO_TDPFD_FK.sql

PROMPT CO_TEPFD_FK.sql
@@CO_TEPFD_FK.sql

PROMPT CO_TPYFD_FK.sql
@@CO_TPYFD_FK.sql

PROMPT CO_TTRAR_FK.sql
@@CO_TTRAR_FK.sql

PROMPT CO_TVLAR_FK.sql
@@CO_TVLAR_FK.sql

PROMPT CO_THARGE_FK.sql
@@CO_THARGE_FK.sql

PROMPT CO_THAROR_FK.sql
@@CO_THAROR_FK.sql

PROMPT CO_THPRCO_FK.sql
@@CO_THPRCO_FK.sql