Prompt 
Prompt Creando FKs en tabla AUT_TSURL

prompt FK_AUT_TSURL_AUT_TSERVICIO

ALTER TABLE "FS_RECAUDOS_US"."AUT_TSURL" 
ADD CONSTRAINT "FK_AUT_TSURL_AUT_TSERVICIO" 
FOREIGN KEY ("SURL_SERVICIO")
REFERENCES "FS_RECAUDOS_US"."AUT_TSERVICIO" ("SERVICIO_SERVICIO") ENABLE;