Prompt 
Prompt Creando FKs en tabla AUT_TSROL

prompt FK_AUT_TSROL_AUT_TROL

ALTER TABLE "FS_RECAUDOS_US"."AUT_TSROL" 
ADD CONSTRAINT "FK_AUT_TSROL_AUT_TROL" 
FOREIGN KEY ("SROL_ROL")
REFERENCES "FS_RECAUDOS_US"."AUT_TROL" ("ROL_ROL") ENABLE;

prompt FK_AUT_TSROL_AUT_TSERVICIO

ALTER TABLE "FS_RECAUDOS_US"."AUT_TSROL" 
ADD CONSTRAINT "FK_AUT_TSROL_AUT_TSERVICIO" 
FOREIGN KEY ("SROL_SERVICIO")
REFERENCES "FS_RECAUDOS_US"."AUT_TSERVICIO" ("SERVICIO_SERVICIO") ENABLE;
