Prompt 
Prompt Creando FKs en tabla CO_TEPFD

prompt Llave Foranea
prompt FK_CO_TEPFD_CO_TFRDP

ALTER TABLE "FS_RECAUDOS_US"."CO_TEPFD" 
ADD CONSTRAINT "FK_CO_TEPFD_CO_TFRDP" 
FOREIGN KEY ("EPFD_FRDP")
REFERENCES "FS_RECAUDOS_US"."CO_TFRDP" ("FRDP_FRDP") ENABLE;