Prompt 
Prompt Creando FKs en tabla CO_TDPFD

prompt Llave Foranea
prompt FK_CO_TDPFD_CO_TFRDP

ALTER TABLE "FS_RECAUDOS_US"."CO_TDPFD" 
ADD CONSTRAINT "FK_CO_TDPFD_CO_TFRDP" 
FOREIGN KEY ("DPFD_FRDP")
REFERENCES "FS_RECAUDOS_US"."CO_TFRDP" ("FRDP_FRDP") ENABLE;