Prompt 
Prompt Creando FKs en tabla CO_TEPSG

prompt Llave Foranea
prompt FK_CO_TEPSG_CO_TTPAR

ALTER TABLE "FS_RECAUDOS_US"."CO_TEPSG" 
ADD CONSTRAINT "FK_CO_TEPSG_CO_TTPAR" 
FOREIGN KEY ("EPSG_TPAR")
REFERENCES "FS_RECAUDOS_US"."CO_TTPAR" ("TPAR_TPAR") ENABLE;