PROMPT CREANDO 01_TABLAS
@@01_TABLAS/UN_TARPR.sql

PROMPT CREANDO 02_SECUENCIAS
@@02_SECUENCIAS/UN_SARPR.sql

PROMPT ALTER 03_ALTER
@@03_ALTER/UN_TARUN.sql
@@03_ALTER/UN_TTPAR.sql

PROMPT CREANDO 04_DATOS
@@04_DATOS/UN_TTPAR_DATA.sql

PROMPT CREANDO 05_FOREIGN_KEY
@@05_FOREIGN_KEY/UN_TARPR_FK.sql



