PROMPT INSERTANDO DATOS EN UDTESIS.AUT_TUSUA

PROMPT ADMINISTRADOR DEL SISTEMA

Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('administrador','DQDQDqAyCoBkBhCSBcDaCNDTAcCHCRCq','udistesis@gmail.com');

Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('ofpaingenieria','ABBBAeBqCbDmB0DkCAB.AJA0BiDUAbAi','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('seacingenieria','DYBGDXDlB2AQDEDXBTAUAWD5DkABDnB2','udistesis@gmail.com');


Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('20042020111','DqBsA6DRBGCMCfCOAMAPArDIDFCJCgDH','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('PUBLICO','PUBLICO','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('123456789','DqBgAlAPCDCADfBZCgAlDxDnDOB0DFDl','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('SYSTEM','DqBsA6DRBGCMCfCOAMAPArDIDFCJCgDH','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('20042020057','A7C0CECPCzDtC2AiB4AcCBBGDbCSCJBx','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('20042020062','D2A.AAAxDPC3C5DKBSCODiDKCBD:BUCA','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('0001','AJABBYChAhCxD7CdBdC4AHC9DRBGCUDY','udsitesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('0002','BFD0DsBpBzA3DcBcAgB5DCDpAeDkAUDc','udistesis@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('0003','CLApD9DaAqDCALDGBUCKDsAeBaDZC:AX','udistesis@gmail.com');

Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('20061025045','CwDfAxADChCrC6B1DKBmB:C6BOBQDgDh','angelaheredia60@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('20042020051','CjBjDeCjBbDUCzDtBLDjA0CLDiBgB0CJ','udistesis@gmail.com');

Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('1010','BeD3DPCXD5APA6BeCQDCCLDZBFDIB3DB','angelaheredia60@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('1011','D9B0BwCfA8BBC3C2DABCD.DPDXCxBRDO','angelaheredia60@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('1012','BMBnCEDFDGBbDgAYAuDUBwCgD3ABAtAs','angelaheredia60@gmail.com');
Insert into UDTESIS.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('1013','BXD8CWD7A2BXC9AYCFD6CFD5BWAkDuDx','angelaheredia60@gmail.com');



commit;