PROMPT INSERTANDO DATOS EN UDTESIS.AUT_TUROL

PROMPT ROLES USUARIO ADMINISTRADOR
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('administrador','ADMIN');

PROMPT ROLES USUARIOS DE PRUEBAS
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('0002','PROF');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('123456789','CORD');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('123456789','PROF');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('20042020111','ESTD');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('20042020062','ESTD');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('20042020057','ESTD');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('PUBLICO','PUB');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('ofpaingenieria','OFPA');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('seacingenieria','SEAC');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('0001','PROF');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('0003','PROF');

Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('20061025045','ESTD');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('20042020051','ESTD');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('1010','CORD');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('1010','PROF');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('1011','PROF');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('1012','PROF');
Insert into UDTESIS.AUT_TUROL (UROL_USUA,UROL_ROL) values ('1013','PROF');

commit;