PROMPT INSERTANDO DATOS EN UDTESIS.AUT_TSROL

PROMPT SERVICIOS ADMINISTRACION


Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (2,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (4,'ADMIN','S');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (200,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (201,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (202,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (203,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (204,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (205,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (206,'ADMIN','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (207,'ADMIN','S');

PROMPT SERVICIOS GENERALES
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (2,'PUB','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (2,'OFPA','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (4,'OFPA','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (2,'ESTD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (4,'ESTD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (2,'CORD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (4,'CORD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (2,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (4,'PROF','S');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (2,'SEAC','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (4,'SEAC','S');

PROMPT
PROMPT SERVICIOS PREPROPUESTA
PROMPT
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (24,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (25,'OFPA','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (26,'OFPA','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (27,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (28,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (29,'OFPA','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (6,'CORD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (7,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (8,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (10,'CORD','S');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (1,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (5,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (7,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (8,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (9,'ESTD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (11,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (23,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (24,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (30,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (32,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (35,'ESTD','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (8,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (12,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (7,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (351,'PROF','S');


PROMPT
PROMPT SERVICIOS PROPUESTA
PROMPT
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (13,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (14,'ESTD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (16,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (20,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (21,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (22,'ESTD','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (15,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (16,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (17,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (18,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (19,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (20,'PROF','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (31,'OFPA','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (32,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (33,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (34,'OFPA','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (36,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (37,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (38,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (38,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (39,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (40,'OFPA','S');

PROMPT
PROMPT SERVICIOS ANTEPROYECTO
PROMPT
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (41,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (43,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (44,'ESTD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (46,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (53,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (55,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (58,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (57,'ESTD','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (43,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (46,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (47,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (48,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (52,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (49,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (54,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (55,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (56,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (58,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (59,'PROF','S');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (42,'CORD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (43,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (45,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (46,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (50,'CORD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (51,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (53,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (600,'CORD','S');

PROMPT
PROMPT SERVICIOS PROYECTO
PROMPT
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (60,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (61,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (62,'ESTD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (63,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (68,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (67,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (70,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (71,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (74,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (76,'ESTD','N');


Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (61,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (64,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (65,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (66,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (68,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (69,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (71,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (72,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (73,'PROF','S');


Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (61,'CORD','N');


Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (75,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (76,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (77,'OFPA','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (78,'OFPA','S');

PROMPT
PROMPT SERVICIOS INFORME FINAL
PROMPT
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (79,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (81,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (82,'ESTD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (84,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (91,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (93,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (96,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (95,'ESTD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (98,'ESTD','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (81,'PROF','N');	
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (84,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (85,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (86,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (90,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (87,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (92,'PROF','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (93,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (94,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (96,'PROF','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (97,'PROF','S');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (80,'CORD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (81,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (83,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (84,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (88,'CORD','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (89,'CORD','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (91,'CORD','N');

Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (99,'SEAC','S');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (81,'SEAC','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (84,'SEAC','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (96,'SEAC','N');
Insert into UDTESIS.AUT_TSROL (SROL_SERVICIO,SROL_ROL,SROL_VISIBLE) values (100,'SEAC','N');


commit;