PROMPT INSERTANDO DATOS EN UDTESIS.GE_TPERN

PROMPT INSERTANDO PERSONA ADMINISTRADOR

Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (0,'Administrador','Administrador','Administrador',1,'0');

Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (12,'Oficina pasantia','Facultad','Ingenieria',1,'11111111112');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (20,'Secretaria Academica','Facultad','Ingenieria',1,'1122334455');

Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (1,'Juan Manuel','Morales','Rodríguez',1,'80833290');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (2,'Julio ','Baron','Velandia',1,'79800000');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (3,'Ana Maria','Peña','Reyes',1,'52000000');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (4,'Alejandro','Daza',null,1,'79900000');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (5,'Mabel','Muñoz',null,1,'51000000');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (6,'Juan Camilo','Vargas','Jerez',1,'1019000000');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (7,'Juan Carlos','Vargas','Vargas',1,'1019000012');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (9,'Adriana Stella','Romero','García',1,'1018000000');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (8,'Yeison Manuel Gerardo','Martínez','Ospina',1,'1032000001');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (10,'Miguel Angel','Mojica','Cáceres',1,'79000000');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (11,'Oscar Armando','Ortiz','Soto',1,'1018000001');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (13,'SYSTEM','SGPG-UD','UDFJC',1,'111122223333');

Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (14,'Sandra Viviana','Heredia','Ramirez',1,'467888778');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (15,'Edilberto','Saenz','Velandia',1,'8765567898');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (16,'Andres','Peña','Reyes',1,'55678987678');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (17,'Camilo','Daza',null,1,'6758857886');
Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (18,'Jose','Muñoz',null,1,'5178000000');

Insert into UDTESIS.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (19,'Estefania','Lopez',null,1,'1515484548');
commit;