PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.AUT_TSERVICIO

PROMPT SERVICIOS ADMINISTRACION

PROMPT SERVICIOS GENERALES

Insert into FS_RECAUDOS_US.AUT_TSERVICIO (SERVICIO_TIPO,SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_ORDEN) values ('O',1,'GE','Inicio de Sesión','Iniciar de Sesión',1);
Insert into FS_RECAUDOS_US.AUT_TSERVICIO (SERVICIO_TIPO,SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_ORDEN) values ('O',2,'GE','Bienvenida','Bienvenida',2);
                                                                                                                           

commit;