PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.AUT_TUSUA

PROMPT ADMINISTRADOR DEL SISTEMA

Insert into FS_RECAUDOS_US.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('administrador','DQDQDqAyCoBkBhCSBcDaCNDTAcCHCRCq','fs_recaudos_us@fs.co');
Insert into FS_RECAUDOS_US.AUT_TUSUA (USUA_USUA,USUA_CLAVE,USUA_MAIL) values ('operador','CqDdC3B8C9ATDWD2ArBlC0CuDRBFA3Cz','fs_recaudos_us@fs.co');


commit;