PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.AUT_TSURL

Insert into FS_RECAUDOS_US.AUT_TSURL (SURL_URL,SURL_SERVICIO,SURL_TIPO) values ('inicio/PageInicio.pub',1,'P');
Insert into FS_RECAUDOS_US.AUT_TSURL (SURL_URL,SURL_SERVICIO,SURL_TIPO) values ('inicio/PageBienvenida.do',2,'P');


commit;