PROMPT AUT_TMODULO_DATA.sql...
@@AUT_TMODULO_DATA.sql

PROMPT AUT_TROL_DATA.sql...
@@AUT_TROL_DATA.sql

PROMPT AUT_TSERVICIO_DATA.sql...
@@AUT_TSERVICIO_DATA.sql

PROMPT AUT_TSROL_DATA.sql...
@@AUT_TSROL_DATA.sql

PROMPT AUT_TSURL_DATA.sql...
@@AUT_TSURL_DATA.sql

PROMPT AUT_TUROL_DATA.sql...
@@AUT_TUROL_DATA.sql

PROMPT AUT_TUSUA_DATA.sql...
@@AUT_TUSUA_DATA.sql

PROMPT GE_TCONFIG_DATA.sql...
@@GE_TCONFIG_DATA.sql

PROMPT GE_TOPER_DATA.sql...
@@GE_TOPER_DATA.sql

PROMPT GE_TPERN_DATA.sql...
@@GE_TPERN_DATA.sql

PROMPT GE_TTDOC_DATA.sql...
@@GE_TTDOC_DATA.sql

PROMPT UN_TEARPU_DATA.sql
@@UN_TEARPU_DATA.sql

PROMPT UN_TEPRUN_DATA.sql
@@UN_TEPRUN_DATA.sql

PROMPT UN_TTPAR_DATA.sql
@@UN_TTPAR_DATA.sql

PROMPT UN_TESTR_DATA.sql
@@UN_TESTR_DATA.sql
