PROMPT CREANDO TABLESPACES
@@00_SCHEMA/01_TABLESPACES.sql

PROMPT CREANDO USER
@@00_SCHEMA/01_USER.sql

PROMPT CREANDO 01_TABLAS
@@01_TABLAS/00_INSTALL.sql

PROMPT CREANDO 02_SECUENCIAS
@@02_SECUENCIAS/00_INSTALL.sql

PROMPT CREANDO 03_FUNCIONES
@@03_FUNCIONES/00_INSTALL.sql

PROMPT CREANDO 04_DATOS
@@04_DATOS/00_INSTALL.sql

PROMPT CREANDO 05_FOREIGN_KEY
@@05_FOREIGN_KEY/00_INSTALL.sql



