PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.AUT_TSERVICIO

PROMPT SERVICIOS ADMINISTRACION

PROMPT SERVICIOS GENERALES

Insert into FS_RECAUDOS_US.AUT_TSERVICIO (SERVICIO_TIPO,SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_ORDEN) values ('O',1,'GE','Inicio de Sesión','Iniciar de Sesión',1);
Insert into FS_RECAUDOS_US.AUT_TSERVICIO (SERVICIO_TIPO,SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_ORDEN) values ('O',2,'GE','Bienvenida','Bienvenida',2);

PROMPT SERVICIOS UNIFICACION ARCHIVOS

PROMPT PROCESAR ARCHIVO
Insert into FS_RECAUDOS_US.AUT_TSERVICIO (SERVICIO_TIPO,SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_ORDEN) values ('O',3,'UN','Unificar Archivos Recaudo','Unificar Archivos Recaudo',1);

PROMPT SERVICIOS CONVERSION ARCHIVOS
Insert into FS_RECAUDOS_US.AUT_TSERVICIO (SERVICIO_TIPO,SERVICIO_SERVICIO,SERVICIO_MODULO,SERVICIO_DESCRI,SERVICIO_NOMB,SERVICIO_ORDEN) values ('O',4,'CO','Conversion Archivos Recaudo','Conversion Archivos Recaudo',1);
                                                                                                                           

commit;