PROMPT INSERTANDO DATOS EN FS_RECAUDOS_US.GE_TPERN

PROMPT INSERTANDO PERSONA ADMINISTRADOR

Insert into FS_RECAUDOS_US.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (0,'Administrador','Administrador','Administrador',1,'0');
Insert into FS_RECAUDOS_US.GE_TPERN (PERN_PERN,PERN_NOMB,PERN_PAPELL,PERN_SAPELL,PERN_TDOC,PERN_DOC) values (1,'Operador','Operador','Operador',1,'1');

commit;