REM ******************************************************************
REM Fecha         : 10/09/2011
REM Realizado por : UDTESIS PROJECT
REM Base de Datos : UDTESIS
REM ******************************************************************

REM TABLESPACE Y SEGMENTOS DE ROLLBACK
set feedback off
spool TMP.lst
select distinct 'pause DEBE estar conectado con Usuario SYSTEM' || chr(10) || 'ROLL' || chr(10) || 'EXIT'
from dual
where user <> 'SYSTEM'
/
spool off
start TMP.lst
set feedback on

REM TABLESPACE TEMPORAL

Create Temporary tablespace UDTESISTEMP TEMPFILE
'C:\oraclexe\oradata\XE\TEMPUDTESIS.dbf' size 300m
         Extent management local uniform size 2m
;


REM TABLESPACE DE DATOS
REM TABLESPACE DE DATOS

CREATE TABLESPACE TS_DUDTESIS DATAFILE 
  'C:\oraclexe\oradata\XE\DUDTESIS.DBF' SIZE 300M AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


REM TABLESPACE DE INDICES 
                                                            
CREATE TABLESPACE TS_IUDTESIS DATAFILE 
  'C:\oraclexe\oradata\XE\IUDTESIS.DBF' SIZE 300M AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;   

REM USUARIO DEL APLICATIVO UDTESIS

drop user UDTESIS cascade;

Create user UDTESIS
 Identified by udtesis
 Default tablespace TS_DUDTESIS
 Temporary tablespace UDTESISTEMP	
 account unlock	
;


Grant 
  ALTER USER, CREATE CLUSTER, CREATE DATABASE LINK, CREATE PROFILE , ALTER PROFILE, 
  CREATE PROCEDURE, CREATE PUBLIC DATABASE LINK, 
  CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, 
  CREATE SESSION, CREATE SYNONYM, CREATE TABLE, 
  CREATE TRIGGER, CREATE USER , CREATE VIEW, 
  DROP PUBLIC SYNONYM, EXECUTE ANY PROCEDURE, 
  SELECT ANY SEQUENCE, SELECT ANY TABLE, 
  UNLIMITED TABLESPACE to UDTESIS
;

Grant Dba To UDTESIS
/
